# Sets up Ubuntu 14.04, downloads security-ansible, and runs it

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "sec-ansible-test"
  
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvvv"
    ansible.playbook = "tests/vagrant.yml"
    ansible.extra_vars = {
      rolename: "../../"
    }
    ansible.skip_tags = ['V-38496']
    ansible.raw_arguments = ['-s']
  end
end